--- #my playbook
- hosts: dev
  user: ron
  become: yes
  gather_facts: yes
  connection: ssh
  vars:
    pkgname: docker
   

  tasks:
    - name: install docker
        action: yum pkg="{{pkgname}}" state=present
        notify: start service
        
   - name: deploy app on docker
      docker-compose:
        project_src: "/mnt/stunning-lamp/"
        stete: present
        scale:
          app: 3

  handlers:
    - name: start service
      action: service name="{{pkgname}}" state=started

    
